PortableTTS:
  model:
    dec_filter_channels: 512
    dec_hidden_dim: 128
    dec_self_attn_kernel_size: 3
    dec_self_attn_n_heads: 4
    dec_self_attn_n_layers: 6
    dec_window_size: 16
    enc_filter_channels: 512
    enc_hidden_dim: 128
    enc_self_attn_kernel_size: 3
    enc_self_attn_n_heads: 2
    enc_self_attn_n_layers: 6
    enc_window_size: 4
    gen_istft_hop_size: 4
    gen_istft_n_fft: 16
    gen_resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    gen_resblock_kernel_sizes:
    - 3
    - 7
    - 11
    gen_upsampe_initial_channel: 128
    gen_upsample_kernel_size:
    - 16
    - 16
    gen_upsample_rates:
    - 8
    - 8
    n_spks: 1
    n_vocab: 414
    pitch_max: 600
    pitch_min: 50
    segment_size: *segment_size
    spk_emb_dim: 128
    va_conv_kernel_size: 3
    va_dropout: 0.5
    va_n_conv_filter: 256
    va_n_pitch_bin: 128
  train:
    batch_size: 16
    betas:
    - 0.8
    - 0.99
    ckpt: null
    coeff_feat_match: 2
    coeff_mel_loss: 45
    discriminator_clip_grad_norm: 5
    epoch: 10000
    eps: 1.0e-08
    generator_clip_grad_norm: 5
    log_interval: 10
    log_mel_interval: 1000
    logdir: log
    lr: 0.0002
    num_workers: 16
    save_interval: 10000
    seed: 123456
    weight_decay: 0.999875
dataset:
  datalist_path: ~/PortableTTS/BZNSYP/fastspeech2/features/train/datalist.jsonl
  hop_size: 256
  mel_f_min: 40
  min_level_db: -100
  n_fft: 1024
  n_mel: 80
  phn2id_path: ~/PortableTTS/BZNSYP/fastspeech2/features/phn2id
  pitch_max: 600
  pitch_min: 50
  preemphasis: 0.97
  ref_level_db: 20
  segment_size: &segment_size 64
  special_tokens_path: ~/PortableTTS/BZNSYP/fastspeech2/features/special_token.txt
  spk2id_path: ~/PortableTTS/BZNSYP/fastspeech2/features/spk2id
  sr: 22050
  win_size: 1024
gpu: 1,2
